# Generated by Django 6.0.1 on 2026-02-04 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiragana', models.CharField(max_length=2, verbose_name='平假名')),
                ('katakana', models.CharField(max_length=2, verbose_name='片假名')),
                ('romaji', models.CharField(max_length=10, verbose_name='罗马音')),
                ('kana_type', models.CharField(choices=[('hira', '平假名'), ('kata', '片假名')], default='hira', max_length=4, verbose_name='假名类型')),
            ],
            options={
                'verbose_name': '假名',
                'verbose_name_plural': '假名表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确次数')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('last_practiced', models.DateTimeField(auto_now=True, verbose_name='最后练习时间')),
                ('kana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kana.kana', verbose_name='假名')),
            ],
            options={
                'verbose_name': '用户进度',
                'verbose_name_plural': '用户进度表',
                'ordering': ['-last_practiced'],
                'unique_together': {('user_id', 'kana')},
            },
        ),
    ]
