# Generated by Django 5.2.10 on 2026-02-16 13:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50, verbose_name='家庭名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '家庭',
                'verbose_name_plural': '家庭',
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否家庭管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='finance_customuser_set', related_query_name='finance_customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='finance_customuser_set', related_query_name='finance_customuser', to='auth.permission', verbose_name='user permissions')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=100, verbose_name='主类目')),
                ('sub_category', models.CharField(max_length=100, verbose_name='子类目')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='是否固定支出')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '支出类目',
                'verbose_name_plural': '支出类目',
                'db_table': 'budget_category',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('liquid', '流动性资产'), ('investment', '投资性资产'), ('self_use', '自用性资产')], max_length=20, verbose_name='资产大类')),
                ('asset_subtype', models.CharField(max_length=50, verbose_name='资产子类')),
                ('asset_name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额（元）')),
                ('yield_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='收益率（%）')),
                ('purchase_time', models.DateField(blank=True, null=True, verbose_name='购置时间')),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='折旧率（%）')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customuser', verbose_name='归属人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('active', '主动收入'), ('passive', '被动收入')], max_length=20, verbose_name='收入类型')),
                ('income_subtype', models.CharField(max_length=50, verbose_name='收入子类')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额（元）')),
                ('payday', models.DateField(verbose_name='到账日期')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
                ('relate_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.asset', verbose_name='关联投资资产')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customuser', verbose_name='归属人')),
            ],
            options={
                'verbose_name': '收入',
                'verbose_name_plural': '收入',
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_type', models.CharField(choices=[('stock', '股票'), ('fund', '基金'), ('bond', '债券'), ('finance', '理财'), ('other', '其他')], max_length=20, verbose_name='投资类型')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='标的代码')),
                ('name', models.CharField(max_length=100, verbose_name='标的名称')),
                ('hold_amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='持有数量')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='成本价')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='当前价')),
                ('yield_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='累计收益率（%）')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='最大回撤（%）')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.asset', verbose_name='关联资产')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '投资标的',
                'verbose_name_plural': '投资标的',
                'db_table': 'investment',
            },
        ),
        migrations.CreateModel(
            name='InvestTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_type', models.CharField(max_length=20, verbose_name='投资类型（同Investment）')),
                ('target_ratio', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='目标占比（%）')),
                ('tolerance_deviation', models.DecimalField(decimal_places=4, default=0.05, max_digits=8, verbose_name='容忍偏离度（默认±5%）')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '投资配置目标',
                'verbose_name_plural': '投资配置目标',
                'db_table': 'invest_target',
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_type', models.CharField(choices=[('mortgage', '按揭类'), ('consumption', '消费类'), ('credit', '信用类')], max_length=20, verbose_name='负债大类')),
                ('liability_subtype', models.CharField(max_length=50, verbose_name='负债子类')),
                ('liability_name', models.CharField(max_length=100, verbose_name='负债名称')),
                ('principal_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='本金余额（元）')),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='利率（%）')),
                ('remaining_term', models.IntegerField(blank=True, null=True, verbose_name='剩余期限（月）')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='月供（元）')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='还款日')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否逾期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customuser', verbose_name='归属人')),
            ],
            options={
                'verbose_name': '负债',
                'verbose_name_plural': '负债',
                'db_table': 'liability',
            },
        ),
        migrations.CreateModel(
            name='ExpendWechat',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='交易ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('trade_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易类目')),
                ('commodity', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品/备注')),
                ('in_out', models.CharField(max_length=10, verbose_name='收支类型（收入/支出）')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额（元）')),
                ('exchange', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易对方')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易状态')),
                ('tenant_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='商户ID')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budgetcategory', verbose_name='关联支出类目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customuser', verbose_name='归属人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '微信账单',
                'verbose_name_plural': '微信账单',
                'db_table': 'expend_wechat',
                'indexes': [models.Index(fields=['family', 'trade_time'], name='idx_wechat_family_time')],
            },
        ),
        migrations.CreateModel(
            name='ExpendMerged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='交易ID')),
                ('expend_channel', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信'), ('manual', '手动录入')], max_length=10, verbose_name='收支渠道')),
                ('commodity', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品/备注')),
                ('in_out', models.CharField(max_length=5, verbose_name='收支类型（收入/支出）')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额（元）')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='交易状态')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budgetcategory', verbose_name='支出类目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customuser', verbose_name='归属人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '合并收支',
                'verbose_name_plural': '合并收支',
                'db_table': 'expend_merged',
                'indexes': [models.Index(fields=['family', 'trade_time'], name='idx_merged_family_time'), models.Index(fields=['in_out'], name='idx_merged_in_out')],
            },
        ),
        migrations.CreateModel(
            name='ExpendAlipay',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='交易ID')),
                ('in_out', models.CharField(max_length=5, verbose_name='收支类型（收入/支出）')),
                ('person_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付宝账号')),
                ('commodity', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品/备注')),
                ('exchange', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易对方')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额（元）')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易状态')),
                ('trade_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易类目')),
                ('tenant_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='商户ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budgetcategory', verbose_name='关联支出类目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customuser', verbose_name='归属人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '支付宝账单',
                'verbose_name_plural': '支付宝账单',
                'db_table': 'expend_alipay',
                'indexes': [models.Index(fields=['family', 'trade_time'], name='idx_alipay_family_time')],
            },
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['family'], name='idx_budget_family'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('family', 'main_category', 'sub_category')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['family', 'update_time'], name='idx_asset_family_update'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='idx_asset_type'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['family', 'payday'], name='idx_income_family_payday'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['family', 'invest_type'], name='idx_invest_family_type'),
        ),
        migrations.AlterUniqueTogether(
            name='investtarget',
            unique_together={('family', 'invest_type')},
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['family', 'update_time'], name='idx_liability_family_update'),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['liability_type'], name='idx_liability_type'),
        ),
    ]
