# Generated by Django 5.2.10 on 2026-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_asset_user_alter_expendmerged_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='绑定邮箱地址'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_configured',
            field=models.BooleanField(default=False, verbose_name='邮箱是否已配置'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱密码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_provider',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='邮箱服务商'),
        ),
    ]
