# Generated by Django 5.2.10 on 2026-02-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_userprofile_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_configured',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_provider',
        ),
    ]
