# Generated by Django 5.2.10 on 2026-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_userprofile_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expendmerged',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='expendmerged',
            name='id',
        ),
        migrations.AddField(
            model_name='expendmerged',
            name='belonging',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='归属'),
        ),
        migrations.AddField(
            model_name='expendmerged',
            name='person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='交易对方'),
        ),
        migrations.AlterField(
            model_name='expendmerged',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='expendmerged',
            name='transaction_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='交易ID'),
        ),
    ]
