# Generated by Django 6.0.1 on 2026-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_expendmerged_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mail_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱密码'),
        ),
    ]
