# Generated by Django 5.2.10 on 2026-02-19 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_userprofile_mail_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celery任务ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('message', models.TextField(blank=True, verbose_name='状态消息')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '导入任务状态',
                'verbose_name_plural': '导入任务状态',
                'db_table': 'import_task_status',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_id'], name='import_task_task_id_2134d1_idx'), models.Index(fields=['user', '-created_at'], name='import_task_user_id_1634a9_idx'), models.Index(fields=['status'], name='import_task_status_67d9e8_idx')],
            },
        ),
    ]
