# Generated by Django 6.0.1 on 2026-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_userprofile_mail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='expendalipay',
            name='belonging',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='expendalipay',
            name='person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='交易方'),
        ),
        migrations.AddField(
            model_name='expendwechat',
            name='belonging',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='expendwechat',
            name='person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='交易方'),
        ),
        migrations.AlterField(
            model_name='expendalipay',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='交易方式'),
        ),
        migrations.AlterField(
            model_name='expendmerged',
            name='belonging',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='expendwechat',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='交易方式'),
        ),
    ]
