# Generated by Django 5.2.10 on 2026-02-22 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expendalipay_belonging_expendalipay_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_type',
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_maintype', models.CharField(max_length=50, verbose_name='收入类型')),
                ('income_subtype', models.CharField(max_length=50, verbose_name='收入子类')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '收入类型',
                'verbose_name_plural': '收入类型',
                'db_table': 'income_type',
            },
        ),
        migrations.AlterField(
            model_name='income',
            name='income_subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.incometype', verbose_name='收入类型'),
        ),
    ]
