# Generated by Django 5.2.10 on 2026-02-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_importtaskstatus'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS import_task_status;",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
