# Generated by Django 5.2.10 on 2026-02-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_income_income_type_incometype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income_subtype',
            new_name='income_type',
        ),
        migrations.AddField(
            model_name='income',
            name='adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='税前调整'),
        ),
        migrations.AddField(
            model_name='income',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='五险一金和税'),
            preserve_default=False,
        ),
    ]
