# Generated by Django 5.2.10 on 2026-02-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rename_income_subtype_income_income_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='insurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='五险一金和税'),
        ),
    ]
