# Generated by Django 5.2.10 on 2026-02-22 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_income_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='税后实到金额（元）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='税前总共金额（元）'),
        ),
        migrations.AlterField(
            model_name='income',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
    ]
