"""
Django settings for Small_Target project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7zltah3jm2sur+&rwg9lvw_vh*hsjt8p&)404mmx$iv^t=py3s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '127.0.0.1',        # 修正笔误：127.0.01 → 127.0.0.1
    'localhost',        # 兼容localhost访问
    'tension601.site',  # 外网域名访问（核心，解决域名访问400）
    '43.137.41.36'      # 公网IP（可选，若需要IP访问则保留）
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'login',
    'kana',
    'project_management',
    'finance',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 跨域中间件
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'login.middleware.auth.AuthMiddleware',  # 启用自定义认证中间件
]

# Allow all origins for development; tighten in production
CORS_ALLOW_ALL_ORIGINS = True
# 允许指定域名(生产环境用)
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]
# 允许携带 Cookie（如需）
CORS_ALLOW_CREDENTIALS = True

# ========== 4. DRF + JWT 配置 ==========
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT 有效期配置
SIMPLE_JWT = {
    # Access Token 有效期（2小时）
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    # Refresh Token 有效期（7天，用于刷新 Access Token）
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # 加密算法
    'ALGORITHM': 'HS256',
    # 密钥（生产环境建议改为环境变量，避免硬编码）
    'SIGNING_KEY': os.environ.get('DJANGO_JWT_SECRET', 'small-target-2024-secret-key-for-jwt-authentication'),
    # 请求头中 Token 的前缀
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# 登录后重定向地址（前端登录页）
LOGIN_URL = 'http://localhost:5173/login'

ROOT_URLCONF = 'Small_Target.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Small_Target.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库HOST动态配置
import os
import socket

def get_database_host():
    """根据运行环境动态确定数据库HOST"""
    # 优先级1: 环境变量直接指定
    custom_host = os.environ.get('DATABASE_HOST')
    if custom_host:
        return custom_host
    
    # 优先级2: 通过部署环境变量判断
    server_ip = '43.137.41.36'
    if os.environ.get('DEPLOY_ENV') == 'production':
        return server_ip
    
    # 优先级3: 通过当前机器IP判断
    try:
        hostname = socket.gethostname()
        local_ip = socket.gethostbyname(hostname)
        if local_ip == server_ip:
            return server_ip
    except:
        pass
    
    # 默认返回本地开发配置
    return 'localhost'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smalltarget',
        'USER': 'postgres',
        'PASSWORD': 'password',
        'HOST': get_database_host(),  # 动态确定数据库地址
        'PORT': '5432',       # PostgreSQL默认端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOG_DIR = BASE_DIR / "logs"
if not LOG_DIR.exists():
    LOG_DIR.mkdir(parents=True, exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file':{
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            # 日志文件放在项目目录，确保有权限写入
            'filename': LOG_DIR.joinpath("django.log").as_posix(),
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        # 'django': {
        #     'handlers': ['file', 'console'],
        #     'level': 'DEBUG',
        #     'propagate': True,
        # },
        'celery': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'login': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
 }
# ========== Celery 配置 ==========
# Broker 设置（开发环境使用内存，生产环境建议使用 Redis）
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'

# 结果后端设置
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'

# 任务序列化设置
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# 时区设置
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = False

# 任务执行设置
CELERY_TASK_ALWAYS_EAGER = False  # False表示异步执行，True表示同步执行（仅用于测试）
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 每个worker预取的任务数
CELERY_TASK_ACKS_LATE = True  # 任务执行完再确认
CELERY_RESULT_EXPIRES = 3600 # 结果1小时后自动删除
CELERY_TASK_TIME_LIMIT = 300  # 任务最长执行5分钟（超时强制终止）
CELERY_TASK_SOFT_TIME_LIMIT = 270  # 软超时：270秒时发送警告，300秒强制终止

# 任务重试配置（网络/临时故障时自动重试）
CELERY_TASK_RETRY_ON_FAILURE = True  # 任务失败时自动重试
CELERY_TASK_MAX_RETRIES = 3  # 最多重试3次
CELERY_TASK_RETRY_DELAY = 5  # 每次重试间隔5秒

CELERY_WORKER_CONCURRENCY = 1 # Windows环境下使用单进程避免权限问题
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # 每个Worker执行1000个任务后自动重启

# 任务路由设置
# CELERY_TASK_ROUTES = {
#     'finance.tasks.import_bill_task': {'queue': 'finance'},
# }

# 任务队列设置
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'
